### ISSUE TITLE
Performing 'INSERT OVERWRITE' for more than 30 partitions at the same time has poor performance

### ISSUE THREAD

**Issue by bright-zy** [ByConity/ByConity#1717]
(you don't have to strictly follow this form)

## Enhancement
Improve multi-partition import performance and reduce the number of parts per partition

**Comment by janplus** [comment]
Could you elaborate your case? Is `INSERT` itself slow or just `INSERT OVERWRITE` slow?

**Comment by bright-zy** [comment]
> Could you elaborate your case? Is `INSERT` itself slow or just `INSERT OVERWRITE` slow?
insert multiple partitions slow
```
INSERT OVERWRITE db.table PARTITION('20240401','20240402','20240403','20240404','20240405','20240406','20240407','20240408','20240409','20240410','20240411','20240412','20240413','20240414','20240415','20240416','20240417','20240418','20240419','20240420','20240421','20240422','20240423','20240424','20240425','20240426','20240427','20240428','20240429','20240430')  ...
```

**Comment by janplus** [comment]
Is it slow without the `OVERWRITE` keyword?

**Comment by bright-zy** [comment]
> Is it slow without the `OVERWRITE` keyword?
Testing imports without OVERWRITE is also slow and is associated with multiple partitions

**Comment by bright-zy** [comment]
At present, there are 3 nodes, can adding vm nodes speed up

**Comment by janplus** [comment]
May be you could try to insert per partition to avoid block been split to multiple parts during insertion, which could decrease the insert performance.

**Comment by bright-zy** [comment]
> May be you could try to insert per partition to avoid block been split to multiple parts during insertion, which could decrease the insert performance.
The performance of each partition is very fast, but the business needs to brush back one month of data, what is the optimization plan for this area

**Comment by janplus** [comment]
Currently you may try to increase `max_block_size`, `min_insert_block_size_rows` and `min_insert_block_size_bytes` to improve the insert performance.

**Comment by bright-zy** [comment]
> Currently you may try to increase `max_block_size`, `min_insert_block_size_rows` and `min_insert_block_size_bytes` to improve the insert performance.
There is some improvement, but it is not very fast compared to other engines, see if there is room for improvement in the bottom layer

**Comment by janplus** [comment]
Parallel insertion is now available. You may try to increase `max_insert_threads` to enable it.

**Comment by bright-zy** [comment]
> Parallel insertion is now available. You may try to increase `max_insert_threads` to enable it.

An error was reported during concurrent execution
```
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 210, host: 10.229.48.1, port: 8123; Code: 210, e.displayText() = DB::Exception: Worker host:10.229.32.30:8124, exception:Code: 210, e.displayText() = DB::Exception: Fail to write HDFS file: /user/bigdata/byconity/disk2/2c87f415-d7df-4db6-935e-16588541ee94/202009_450676999778992135_450676999778992135_0_450676993624637450_0/data HdfsIOException: Unexpected exception: when unwrap the rpc remote exception "org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException", INode is not a regular file: / (inode 0) [Lease.  Holder: libhdfs3_client_random_568409658_count_6416652_pid_9_tid_139304988813056, pending creates: 1]
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2880)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.abandonBlock(FSDirWriteFileOp.java:123)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.abandonBlock(FSNamesystem.java:2854)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.abandonBlock(NameNodeRpcServer.java:966)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.abandonBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:562)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1045)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:963)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): INode is not a regular file: / (inode 0) [Lease.  Holder: libhdfs3_client_random_568409658_count_6416652_pid_9_tid_139304988813056, pending creates: 1]
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2880)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.abandonBlock(FSDirWriteFileOp.java:123)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.abandonBlock(FSNamesystem.java:2854)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.abandonBlock(NameNodeRpcServer.java:966)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.abandonBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:562)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1045)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:963)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1554)
	at org.apache.hadoop.ipc.Client.call(Client.java:1492)
	at org.apache.hadoop.ipc.Client.call(Client.java:1389)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:233)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:118)
	at com.sun.proxy.$Proxy19.abandonBlock(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.abandonBlock(ClientNamenodeProtocolTranslatorPB.java:495)
	at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invoke(RouterRpcClient.java:557)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeMethod(RouterRpcClient.java:457)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSingle(RouterRpcClient.java:746)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSingleBlockPool(RouterRpcClient.java:718)
	at org.apache.hadoop.hdfs.server.federation.router.RouterRpcClient.invokeSingle(RouterR: While executing TableWrite SQLSTATE: 08000 (version 21.8.7.1) SQLSTATE: 08000 (version 21.8.7.1)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:815)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:611)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:114)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:97)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:92)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:87)
	at com.bigdata.databus.spark.sink.byconity.ByconitySink.executeSql(ByconitySink.java:382)
	at com.bigdata.databus.spark.sink.byconity.ByconitySink.loadByconity(ByconitySink.java:193)
	at com.bigdata.databus.spark.sink.byconity.ByconitySink.write(ByconitySink.java:98)
	at com.bigdata.databus.spark.batch.SparkBatchJob.start(SparkBatchJob.java:54)
	at com.bigdata.databus.core.JobContainer.start(JobContainer.java:52)
	at com.bigdata.databus.core.Driver.main(Driver.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:739)
```

**Comment by enjay-s** [comment]
no update? @janplus
