### ISSUE TITLE
insert语句携带with子查询时会报错

### ISSUE THREAD

**Issue by xinip** [ByConity/ByConity#1736]
### 重现如下
CREATE TABLE IF NOT EXISTS test.abc  (
  a String,
  b String,
  c String
) 
ENGINE = CnchMergeTree()
PARTITION BY (a)
ORDER BY (b)
;

CREATE TABLE IF NOT EXISTS test.def  (
  d String,
  e String,
  f String
) 
ENGINE = CnchMergeTree()
PARTITION BY (d)
ORDER BY (e)
;

INSERT INTO test.abc VALUES ( 'a1', 'b1', 'c1');

-- select可以正常执行：

with a as (
 select a,b,c
  from abc
)

SELECT a,b,c
from a ;

-- insert语句报错

with a as (
 select a,b,c
  from abc
)

insert into test.def
SELECT a,b,c
from a ;

报错信息如下：

java.sql.SQLException: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 41 ('insert') (line 6, col 1): insert into test.def
SELECT a,b,c
from a . Expected one of: SELECT, Comma, token SQLSTATE: 42000 (version 21.8.7.1)
, server ClickHouseNode [uri=http://172.24.150.135:8123/test, options={socket_timeout=300000}]@1412671414
at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:139)
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:491)
at com.xsj.whale.query.engine.client.JdbcClient.exec(JdbcClient.java:224)
at com.xsj.whale.query.engine.client.JdbcClient.main(JdbcClient.java:54)
Caused by: java.io.IOException: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 41 ('insert') (line 6, col 1): insert into test.def
SELECT a,b,c
from a . Expected one of: SELECT, Comma, token SQLSTATE: 42000 (version 21.8.7.1)

at com.clickhouse.client.http.ApacheHttpConnectionImpl.checkResponse(ApacheHttpConnectionImpl.java:222)
at com.clickhouse.client.http.ApacheHttpConnectionImpl.post(ApacheHttpConnectionImpl.java:261)
at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:195)
at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:878)
at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:137)
... 3 more

**Comment by liyinsg** [comment]
```sql
insert into test.def
with a as (
select a,b,c
from test.abc
)
SELECT a,b,c
from a ;
```
