### ISSUE TITLE
dolphinscheduler3.1.8版本连接Byconity执行bitmapBuild([1, 2, 3, 4, 5])报错

### ISSUE THREAD

**Issue by xiongbl526** [ByConity/ByConity#1829]
(you don't have to strictly follow this form)

## Question
byconity版本0.4.2 k8s部署
dolphinscheduler上连接23.4版本clickhouse执行SELECT bitmapBuild([1, 2, 3, 4, 5]) AS res 响应正常，
连接bcyontiy执行就会报错java.lang.NoClassDefFoundError: Could not initialize class com.clickhouse.client.data.ClickHouseBitmap

**Comment by nudles** [comment]
@xiongbl526  请问你是通过clickhouse的jdbc driver连接的吗？

**Comment by xiongbl526** [comment]
对的 clickhouse-jdbc-0.3.2-patch11版本



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年08月28日 11:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] dolphinscheduler3.1.8版本连接Byconity执行bitmapBuild([1, 2, 3, 4, 5])报错 (Issue #1829) |

@xiongbl526 请问你是通过clickhouse的jdbc driver连接的吗？

**Comment by xiongbl526** [comment]
我用了更高版本的0.4.6版本也还是不行



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年08月28日 11:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] dolphinscheduler3.1.8版本连接Byconity执行bitmapBuild([1, 2, 3, 4, 5])报错 (Issue #1829) |

@xiongbl526 请问你是通过clickhouse的jdbc driver连接的吗？

**Comment by nudles** [comment]
@xiongbl526 请问有完整的call stack吗

**Comment by xiongbl526** [comment]
> @xiongbl526 请问有完整的call stack吗
辛苦看下
[bigtmap.log](https://github.com/user-attachments/files/16778099/bigtmap.log)

**Comment by nudles** [comment]
@xiongbl526  这个报错是哪个版本的jdbc. 我看这个版本https://github.com/ClickHouse/clickhouse-java/blob/v0.6.4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmapValue.java#L40 这里不应该报错的。

**Comment by xiongbl526** [comment]
0.3.2-patch11版本的



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年08月28日 17:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] dolphinscheduler3.1.8版本连接Byconity执行bitmapBuild([1, 2, 3, 4, 5])报错 (Issue #1829) |

@xiongbl526 这个报错是哪个版本的jdbc. 我看这个版本https://github.com/ClickHouse/clickhouse-java/blob/v0.6.4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmapValue.java#L40 这里不应该报错的。

**Comment by xiongbl526** [comment]
> @xiongbl526 这个报错是哪个版本的jdbc. 我看这个版本https://github.com/ClickHouse/clickhouse-java/blob/v0.6.4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmapValue.java#L40 这里不应该报错的。
我把clickhouse-jdbc包换成0.6.4报错下面这个
[INFO] 2024-08-28 19:07:15.148 +0800 - can't find udf function resource
[INFO] 2024-08-28 19:07:15.618 +0800 - prepare statement replace sql : SELECT bitmapBuild([1, 2, 3, 4, 5]) AS res settings enable_optimizer = 1, sql parameters : {}
[ERROR] 2024-08-28 19:07:15.751 +0800 - Task execute failed, due to meet an exception
java.lang.NoClassDefFoundError: org/roaringbitmap/buffer/ImmutableRoaringBitmap
	at com.clickhouse.client.data.ClickHouseBitmap.<clinit>(ClickHouseBitmap.java:24)
	at com.clickhouse.client.data.ClickHouseBitmapValue.ofEmpty(ClickHouseBitmapValue.java:40)
	at com.clickhouse.client.data.ClickHouseBitmapValue.ofEmpty(ClickHouseBitmapValue.java:29)
	at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:1151)
	at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:1024)
	at com.clickhouse.client.ClickHouseDataProcessor.<init>(ClickHouseDataProcessor.java:313)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor.<init>(ClickHouseRowBinaryProcessor.java:571)
	at com.clickhouse.client.ClickHouseDataStreamFactory.getProcessor(ClickHouseDataStreamFactory.java:57)
	at com.clickhouse.client.data.ClickHouseStreamResponse.<init>(ClickHouseStreamResponse.java:76)
	at com.clickhouse.client.data.ClickHouseStreamResponse.of(ClickHouseStreamResponse.java:53)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:126)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:296)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:351)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:824)
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:1972)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:160)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeAny(SqlBasedPreparedStatement.java:198)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeQuery(SqlBasedPreparedStatement.java:235)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeQuery(SqlTask.java:306)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:209)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:163)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:49)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.roaringbitmap.buffer.ImmutableRoaringBitmap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 32 common frames omitted

**Comment by nudles** [comment]
> > @xiongbl526 这个报错是哪个版本的jdbc. 我看这个版本https://github.com/ClickHouse/clickhouse-java/blob/v0.6.4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmapValue.java#L40 这里不应该报错的。
> > 我把clickhouse-jdbc包换成0.6.4报错下面这个
> > [INFO] 2024-08-28 19:07:15.148 +0800 - can't find udf function resource
> > [INFO] 2024-08-28 19:07:15.618 +0800 - prepare statement replace sql : SELECT bitmapBuild([1, 2, 3, 4, 5]) AS res settings enable_optimizer = 1, sql parameters : {}
> > [ERROR] 2024-08-28 19:07:15.751 +0800 - Task execute failed, due to meet an exception
> > java.lang.NoClassDefFoundError: org/roaringbitmap/buffer/ImmutableRoaringBitmap
> > at com.clickhouse.client.data.ClickHouseBitmap.(ClickHouseBitmap.java:24)
> > at com.clickhouse.client.data.ClickHouseBitmapValue.ofEmpty(ClickHouseBitmapValue.java:40)
> > at com.clickhouse.client.data.ClickHouseBitmapValue.ofEmpty(ClickHouseBitmapValue.java:29)
> > at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:1151)
> > at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:1024)
> > at com.clickhouse.client.ClickHouseDataProcessor.(ClickHouseDataProcessor.java:313)
> > at com.clickhouse.client.data.ClickHouseRowBinaryProcessor.(ClickHouseRowBinaryProcessor.java:571)
> > at com.clickhouse.client.ClickHouseDataStreamFactory.getProcessor(ClickHouseDataStreamFactory.java:57)
> > at com.clickhouse.client.data.ClickHouseStreamResponse.(ClickHouseStreamResponse.java:76)
> > at com.clickhouse.client.data.ClickHouseStreamResponse.of(ClickHouseStreamResponse.java:53)
> > at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:126)
> > at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
> > at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)
> > at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:296)
> > at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:351)
> > at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:824)
> > at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:1972)
> > at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:160)
> > at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeAny(SqlBasedPreparedStatement.java:198)
> > at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeQuery(SqlBasedPreparedStatement.java:235)
> > at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeQuery(SqlTask.java:306)
> > at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:209)
> > at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:163)
> > at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:49)
> > at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:174)
> > at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> > at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
> > at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
> > at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> > at java.lang.Thread.run(Thread.java:750)
> > Caused by: java.lang.ClassNotFoundException: org.roaringbitmap.buffer.ImmutableRoaringBitmap
> > at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> > at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> > ... 32 common frames omitted

0.6.4 的错误应该是这里 https://github.com/ClickHouse/clickhouse-java/blob/v0.6.4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmap.java#L15
没有安装这个包吧

**Comment by xiongbl526** [comment]
请问有什么好的办法嘛？



---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 日期 | 2024年08月29日 10:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ByConity/ByConity] dolphinscheduler3.1.8版本连接Byconity执行bitmapBuild([1, 2, 3, 4, 5])报错 (Issue #1829) |

@xiongbl526 这个报错是哪个版本的jdbc. 我看这个版本https://github.com/ClickHouse/clickhouse-java/blob/v0.6.4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmapValue.java#L40 这里不应该报错的。
我把clickhouse-jdbc包换成0.6.4报错下面这个
[INFO] 2024-08-28 19:07:15.148 +0800 - can't find udf function resource
[INFO] 2024-08-28 19:07:15.618 +0800 - prepare statement replace sql : SELECT bitmapBuild([1, 2, 3, 4, 5]) AS res settings enable_optimizer = 1, sql parameters : {}
[ERROR] 2024-08-28 19:07:15.751 +0800 - Task execute failed, due to meet an exception
java.lang.NoClassDefFoundError: org/roaringbitmap/buffer/ImmutableRoaringBitmap
at com.clickhouse.client.data.ClickHouseBitmap.(ClickHouseBitmap.java:24)
at com.clickhouse.client.data.ClickHouseBitmapValue.ofEmpty(ClickHouseBitmapValue.java:40)
at com.clickhouse.client.data.ClickHouseBitmapValue.ofEmpty(ClickHouseBitmapValue.java:29)
at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:1151)
at com.clickhouse.client.ClickHouseValues.newValue(ClickHouseValues.java:1024)
at com.clickhouse.client.ClickHouseDataProcessor.(ClickHouseDataProcessor.java:313)
at com.clickhouse.client.data.ClickHouseRowBinaryProcessor.(ClickHouseRowBinaryProcessor.java:571)
at com.clickhouse.client.ClickHouseDataStreamFactory.getProcessor(ClickHouseDataStreamFactory.java:57)
at com.clickhouse.client.data.ClickHouseStreamResponse.(ClickHouseStreamResponse.java:76)
at com.clickhouse.client.data.ClickHouseStreamResponse.of(ClickHouseStreamResponse.java:53)
at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:126)
at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)
at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:296)
at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:351)
at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:824)
at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:1972)
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:160)
at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeAny(SqlBasedPreparedStatement.java:198)
at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeQuery(SqlBasedPreparedStatement.java:235)
at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeQuery(SqlTask.java:306)
at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:209)
at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.handle(SqlTask.java:163)
at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:49)
at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:174)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.roaringbitmap.buffer.ImmutableRoaringBitmap
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 32 common frames omitted

0.6.4 的错误应该是这里 https://github.com/ClickHouse/clickhouse-java/blob/v0.6.4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseBitmap.java#L15
没有安装这个包吧
