### ISSUE TITLE
 版本从 0.1.2 升级到 0.2.0， S3 存储的表无法查询

### ISSUE THREAD

**Issue by hillbun** [ByConity/ByConity#691]
版本从 0.1.2 升级到 0.2.0， S3 存储的表无法查询

```
select * from store2 limit 1;

SELECT *
FROM store2
LIMIT 1

Query id: df353819-1fc9-4bdf-9288-d6074ac99881


0 rows in set. Elapsed: 0.053 sec. 

Received exception from server (version 21.8.7):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: DB::Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: , ExceptionName: , ErrorMessage: No response body., Extra:  SQLSTATE: HY000.: While executing Remote SQLSTATE: HY000. 
```

**Comment by FourSpaces** [comment]
https://byconity.github.io/docs/advanced-guide/0.2.0_s3_upgrade_checklist

**Comment by dmthuc** [comment]
Hi @white-cc , please help on this issue

**Comment by dmthuc** [comment]
> https://byconity.github.io/docs/advanced-guide/0.2.0_s3_upgrade_checklist

Hi @FourSpaces , could you help to execute `set send_logs_level='trace'` then execute the query again. We would like to have some log that can help with the debug

**Comment by white-cc** [comment]
There is a break change for S3 storage. We change the relative path for S3 storage to mutate part better. 
please use ./clickhouse s3-rename after upgrade. 
https://byconity.github.io/docs/advanced-guide/0.2.0_s3_upgrade_checklist

**Comment by hillbun** [comment]
I   run  after upgrade
clickhouse s3-rename --s3_ak_id  xxxx --s3_ak_secret xxxxx --from_bucket xxxx --s3_endpoint https://cos.ap-singapore.myqcloud.com --s3_region ap-singapore --root_prefix byconity

and config is

    server_s3_disk0:
      ak_id: xxxx
      ak_secret: xxxx
      bucket: xxxxxx
      endpoint: https://cos.ap-singapore.myqcloud.com
      path: byconity
      region: ap-singapore
      type: bytes3
      is_virtual_hosted_style: true



```
10.0.3.134 :) set send_logs_level='trace'

SET send_logs_level = 'trace'

Query id: cd18b31f-8829-4ac0-a5b5-6d6014132311

Ok.

0 rows in set. Elapsed: 0.002 sec. 

10.0.3.134 :) 
10.0.3.134 :) 
10.0.3.134 :) 
10.0.3.134 :) select * from store2 limit 2;

SELECT *
FROM store2
LIMIT 2

Query id: d458f1ff-eb07-4e89-9b9b-70ecc68796a1

[byconity-server-0] 2023.09.18 11:21:30.292714 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> executeQuery: Extract db and table .store2 from the query.
[byconity-server-0] 2023.09.18 11:21:30.293698 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> DatabaseCnch (test): Create database test in query 
[byconity-server-0] 2023.09.18 11:21:30.295366 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> executeQuery: target server is 10.0.3.134:8124 and local rpc port is 8124
[byconity-server-0] 2023.09.18 11:21:30.295740 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> TransactionCoordinator: Created txn txn_id: 444335991103422466 commit_ts: 0 status: Running priority: high location: "10.0.3.134:8124" initiator: "Server" type: Implicit

[byconity-server-0] 2023.09.18 11:21:30.296675 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> DatabaseCnch (test): Create database test in query 
[byconity-server-0] 2023.09.18 11:21:30.297568 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> trySetVirtualWarehouse: try get warehouse from vw_default, type is WRITE false
[byconity-server-0] 2023.09.18 11:21:30.298088 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> adaptiveScheduler: getWorkerGroups response: is_leader: true worker_group_data { id: "vw_default" type: 1 vw_uuid { low: 13550088662373975693 high: 10643168071322455787 } vw_name: "vw_default" host_ports_vec { hostname: "byconity-vw-vw-default-0" host: "10.0.7.76" rpc_port: 8124 tcp_port: 9000 http_port: 8123 exchange_port: 8124 exchange_status_port: 8124 } num_workers: 1 metrics { id: "vw_default" worker_metrics_vec { id: "byconity-vw-vw-default-0" cpu_1min: 0 mem_1min: 0 num_queries: 0 num_manipulations: 0 num_consumers: 0 num_dedups: 0 } } is_auto_linked: false }
[byconity-server-0] 2023.09.18 11:21:30.298147 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> vw_default (VirtualWarehouseHandle): adaptive updateWorkerStatusFromRM
[byconity-server-0] 2023.09.18 11:21:30.298208 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> executeQuery: (from [::1]:35042, user: chainmodeling) select * from store2 limit 2;
[byconity-server-0] 2023.09.18 11:21:30.298631 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> ContextAccess (chainmodeling): Access granted: SELECT(b) ON test.store2
[byconity-server-0] 2023.09.18 11:21:30.298674 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> InterpreterSelectQuery: query: SELECT b FROM store2 LIMIT 2
[byconity-server-0] 2023.09.18 11:21:30.299168 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> Catalog: test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952) Start handle intermediate parts. Total number of parts is 17, timestamp: 444335991103422466
[byconity-server-0] 2023.09.18 11:21:30.299211 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> Catalog: test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952) Finish handle intermediate parts. Total number of parts is 17, timestamp: 444335991103422466
[byconity-server-0] 2023.09.18 11:21:30.299233 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> Catalog: Elapsed 0ms to get 17 parts in 1 partitions for table : test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952) , source : PartCache, ts : 444335991103422466
[byconity-server-0] 2023.09.18 11:21:30.299249 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952): Total number of parts get from bytekv: 17
[byconity-server-0] 2023.09.18 11:21:30.299316 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> calcVisiblePartsImpl: all_parts:
 all_444068437235335168_444068448219168773_1_444068462650195968 d=0 p=0 h=0
all_444068448481312772_444068448481312772_0_444068437222227968 d=0 p=0 h=0
all_444068448717242372_444068460592103428_1_444068462374944775 d=0 p=0 h=0
all_444068496925523970_444068497423597589_1_444068511225217034 d=0 p=0 h=0
all_444068497436704768_444068497449811969_1_444069128535277575 d=0 p=0 h=0
all_444068497462919175_444068498013159429_1_444068499926810631 d=0 p=0 h=0
all_444068500202323970_444068501040922632_1_444068503085907975 d=0 p=0 h=0
all_444068501040922637_444068501735866379_1_444068516769824776 d=0 p=0 h=0
all_444068501748973575_444068525735149572_2_444068527805825031 d=0 p=0 h=0
all_444068525748256772_444068526665760772_2_444068541752147968 d=0 p=0 h=0
all_444068526678867974_444068576237191181_2_444068579042131975 d=0 p=0 h=0
all_444068576237191182_444068576577978383_1_444068579579527176 d=0 p=0 h=0
all_444068576603930640_444068577036730376_1_444068579317121026 d=0 p=0 h=0
all_444273792513212416_444273794374434816_1_444273796615766024 d=0 p=0 h=0
all_444273794400649221_444273794479292420_1_444274427072086023 d=0 p=0 h=0
all_444273794505506827_444273796274978821_1_444273796877647889 d=0 p=0 h=0
all_444273836776226817_444273836776226817_0_444273836763119616 d=0 p=0 h=0

[byconity-server-0] 2023.09.18 11:21:30.299381 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> calcVisiblePartsImpl: visible_parts (skip_drop_ranges=true):
all_444068437235335168_444068448219168773_1_444068462650195968 d=0 p=0 h=0
all_444068448481312772_444068448481312772_0_444068437222227968 d=0 p=0 h=0
all_444068448717242372_444068460592103428_1_444068462374944775 d=0 p=0 h=0
all_444068496925523970_444068497423597589_1_444068511225217034 d=0 p=0 h=0
all_444068497436704768_444068497449811969_1_444069128535277575 d=0 p=0 h=0
all_444068497462919175_444068498013159429_1_444068499926810631 d=0 p=0 h=0
all_444068500202323970_444068501040922632_1_444068503085907975 d=0 p=0 h=0
all_444068501040922637_444068501735866379_1_444068516769824776 d=0 p=0 h=0
all_444068501748973575_444068525735149572_2_444068527805825031 d=0 p=0 h=0
all_444068525748256772_444068526665760772_2_444068541752147968 d=0 p=0 h=0
all_444068526678867974_444068576237191181_2_444068579042131975 d=0 p=0 h=0
all_444068576237191182_444068576577978383_1_444068579579527176 d=0 p=0 h=0
all_444068576603930640_444068577036730376_1_444068579317121026 d=0 p=0 h=0
all_444273792513212416_444273794374434816_1_444273796615766024 d=0 p=0 h=0
all_444273794400649221_444273794479292420_1_444274427072086023 d=0 p=0 h=0
all_444273794505506827_444273796274978821_1_444273796877647889 d=0 p=0 h=0
all_444273836776226817_444273836776226817_0_444273836763119616 d=0 p=0 h=0

[byconity-server-0] 2023.09.18 11:21:30.299401 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Information> test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952): Number of parts get from catalog: 17
[byconity-server-0] 2023.09.18 11:21:30.299444 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Information> test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952): Number of parts to read: 17
[byconity-server-0] 2023.09.18 11:21:30.299937 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> ContextAccess (chainmodeling): Access granted: SELECT(b) ON test.store2
[byconity-server-0] 2023.09.18 11:21:30.300014 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> InterpreterSelectQuery: query: SELECT b FROM store2 LIMIT 2
[byconity-server-0] 2023.09.18 11:21:30.300080 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952): Original query before rewrite: SELECT b FROM store2 LIMIT 2
[byconity-server-0] 2023.09.18 11:21:30.300127 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> test.store2 (af2c29e6-7706-43f9-a34e-1047522c7952): After query rewrite: SELECT store2_444335991103422466.b FROM test.store2_444335991103422466 LIMIT 2
[byconity-server-0] 2023.09.18 11:21:30.300223 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> InterpreterSelectQuery: Complete -> Complete
[byconity-server-0] 2023.09.18 11:21:30.300271 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> QueryPlan: Build pipeline takes:0
[byconity-server-0] 2023.09.18 11:21:30.300322 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> executeQuery: pipeline has all used StorageIDs: true
[byconity-server-0] 2023.09.18 11:21:30.300573 [ 25561 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> Connection (10.0.7.76:9000): Connecting. Database: default. User: server
[byconity-server-0] 2023.09.18 11:21:30.303094 [ 25561 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Trace> Connection (10.0.7.76:9000): Connected to ByConity server version 21.8.7.
[byconity-server-0] 2023.09.18 11:21:30.303355 [ 25561 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Information> Strict Bounded Consistent Hash: Start to allocate part with bounded ring based hash policy under strict mode 1.
[byconity-server-0] 2023.09.18 11:21:30.303460 [ 25561 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Information> Strict Bounded Consistent Hash: Finish allocate part with strict bounded ring based hash policy under strict mode 1.
[byconity-server-0] 2023.09.18 11:21:30.303498 [ 25561 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> Strict Consistent Hash: byconity-vw-vw-default-0 -> 17; stats: 0 1

[byconity-server-0] 2023.09.18 11:21:30.345460 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Debug> TransactionCoordinator: Deleted txn 444335991103422466
[byconity-server-0] 2023.09.18 11:21:30.345581 [ 25321 ] {d458f1ff-eb07-4e89-9b9b-70ecc68796a1} <Error> executeQuery: Code: 499, e.displayText() = DB::Exception: DB::Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: , ExceptionName: , ErrorMessage: No response body., Extra:  SQLSTATE: HY000.: While executing Remote SQLSTATE: HY000 (version 21.8.7.1) (from [::1]:35042) (in query: select * from store2 limit 2;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1c594a12 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xc85b4e0 in /opt/byconity/bin/clickhouse
2. DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) @ 0xc8c4f2f in /opt/byconity/bin/clickhouse
3. DB::RPCHelpers::checkException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x162abdeb in /opt/byconity/bin/clickhouse
4. void DB::RPCHelpers::onAsyncCallDoneWithFailedInfo<DB::Protos::SendResourcesResp>(DB::Protos::SendResourcesResp*, brpc::Controller*, std::__1::shared_ptr<DB::ExceptionHandlerWithFailedInfo>, DB::WorkerId) @ 0x16101b0a in /opt/byconity/bin/clickhouse
5. brpc::internal::FunctionClosure4<DB::Protos::SendResourcesResp*, brpc::Controller*, std::__1::shared_ptr<DB::ExceptionHandlerWithFailedInfo>, DB::WorkerId>::Run() @ 0x161038c1 in /opt/byconity/bin/clickhouse
6. brpc::Controller::EndRPC(brpc::Controller::CompletionInfo const&) @ 0x184e2dc9 in /opt/byconity/bin/clickhouse
7. brpc::Controller::OnVersionedRPCReturned(brpc::Controller::CompletionInfo const&, bool, int) @ 0x184e1926 in /opt/byconity/bin/clickhouse
8. brpc::policy::ProcessRpcResponse(brpc::InputMessageBase*) @ 0x1850ad90 in /opt/byconity/bin/clickhouse
9. brpc::InputMessenger::OnNewMessages(brpc::Socket*) @ 0x1850164e in /opt/byconity/bin/clickhouse
10. brpc::Socket::ProcessEvent(void*) @ 0x18630eed in /opt/byconity/bin/clickhouse
11. bthread::TaskGroup::task_runner(long) @ 0x184cf2ad in /opt/byconity/bin/clickhouse


0 rows in set. Elapsed: 0.055 sec. 

Received exception from server (version 21.8.7):
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: DB::Exception: Encounter exception when request s3, HTTP Code: 404, RemoteHost: , RequestID: , ExceptionName: , ErrorMessage: No response body., Extra:  SQLSTATE: HY000.: While executing Remote SQLSTATE: HY000. 

10.0.3.134 :) 
```

**Comment by FourSpaces** [comment]
> > https://byconity.github.io/docs/advanced-guide/0.2.0_s3_upgrade_checklist
> 
> Hi @FourSpaces , could you help to execute `set send_logs_level='trace'` then execute the query again. We would like to have some log that can help with the debug

OK, I'll test it today

**Comment by hillbun** [comment]
@white-cc    @dmthuc 

PLease advice

**Comment by FourSpaces** [comment]
@white-cc @dmthuc  
1. I am using a volcanic cloud. After running the s3 rename tool, I am unable to know the running status and results, nor can I set the log enable_ Logging, if this tool is available in AWS S3, it is estimated that VirtualHostStyle needs to be set. I did not notice any changes in the object storage.


2. The s3-meta-sanitizer tool does not support. yaml files, which requires configuration support.
I did not successfully migrate the data from 0.1.2 to 0.2.0

**Comment by hillbun** [comment]
> * I am using a volcanic cloud. After running the s3 rename tool, I am unable to know the running status and results, nor can I set the log enable_ Logging, if this tool is available in AWS S3, it is estimated that VirtualHostStyle needs to be set. I did not notice any changes in the object storage.

I notice that data files in S3 storage update time are updated after run clickhouse s3-rename command


> * The s3-meta-sanitizer tool does not support. yaml files, which requires configuration support.
>   I did not successfully migrate the data from 0.1.2 to 0.2.0

config file name of k8s deploy is /etc/byconity/cnch-config.yaml 

it should be supported.

**Comment by hillbun** [comment]
```
clickhouse s3-meta-sanitizer -C /etc/byconity/cnch-config.yaml
libc++abi: terminating with uncaught exception of type Poco::InvalidArgumentException: Invalid argument
Aborted (core dumped)
```

**Comment by gaodayue** [comment]
@hillbun could you provide the cnch-config.yaml file with sensitive info removed/masked?

**Comment by hillbun** [comment]
@gaodayue 



```
/etc/byconity/cnch-config.yaml 
catalog:
  name_space: byconity
catalog_service:
  fdb:
    cluster_file: /etc/byconity/fdb/cluster-file
  type: fdb
cnch_type: server
exchange_port: 9410
exchange_status_port: 9510
hdfs_addr: hdfs://byconity-hdfs-namenodes:8020
http_port: 8123
rpc_port: 8124
service_discovery:
  cluster: default
  daemon_manager:
    headless_service: byconity-daemon-manager-headless
    psm: byconity-daemon-manager
    service: byconity-daemon-manager
  mode: dns
  resource_manager:
    headless_service: byconity-resource-manager-headless
    psm: byconity-resource-manager
    service: byconity-resource-manager
  server:
    headless_service: byconity-server-headless
    psm: byconity-server
    service: byconity-server
  tso:
    headless_service: byconity-tso-headless
    psm: byconity-tso
    service: byconity-tso
  vw: {}
tcp_port: 9000
tso_service:
  tso_get_leader_info_interval_ms: 0
  tso_max_retry_count: 3
  tso_window_ms: 3000
```

**Comment by gaodayue** [comment]
@hillbun I tried you config file locally but couldn't reproduce the issue. Could you run the tool under gdb to get the stacktrace of the core?

**Comment by hillbun** [comment]
How to do this?

**Comment by gaodayue** [comment]
@hillbun 
1. execute `gdb clickhouse`
2. inside gdb, execute `start s3-meta-sanitizer -C /etc/byconity/cnch-config.yaml` and then `continue`

**Comment by hillbun** [comment]
```
kubectl exec -it byconity-server-0   -n kaya-dev bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@byconity-server-0:/# gdb clickhouse
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from clickhouse...
(no debugging symbols found)...done.
(gdb) 
(gdb) start s3-meta-sanitizer -C /etc/byconity/cnch-config.yaml
Temporary breakpoint 1 at 0xc853ae4 (14 locations)
Starting program: /opt/byconity/bin/clickhouse s3-meta-sanitizer -C /etc/byconity/cnch-config.yaml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5fdf700 (LWP 416204)]
[New Thread 0x7ffff555e700 (LWP 416205)]
[New Thread 0x7ffff47ff700 (LWP 416206)]
[New Thread 0x7ffff3ffe700 (LWP 416207)]
[New Thread 0x7ffff37fd700 (LWP 416208)]

Thread 1 "clickhouse" hit Temporary breakpoint 1, 0x000000000c853ae4 in main ()
(gdb) c
Continuing.
libc++abi: terminating with uncaught exception of type Poco::InvalidArgumentException: Invalid argument

Thread 1 "clickhouse" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff69fe535 in __GI_abort () at abort.c:79
#2  0x000000001c87b8e1 in ?? ()
#3  0x000000001c87a8ca in ?? ()
#4  0x000000001c893d08 in ?? ()
#5  0x000000001c89329b in ?? ()
#6  0x000000001c893212 in __cxa_throw ()
#7  0x000000001c519723 in Poco::Util::Application::loadConfiguration(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) ()
#8  0x000000000cab0099 in DB::S3MetaSanitizer::initialize(Poco::Util::Application&) ()
#9  0x000000001c519c9b in Poco::Util::Application::run() ()
#10 0x000000000cab1b3f in mainEntryClickhouseS3MetaSanitizer(int, char**) ()
#11 0x000000000c854128 in main ()
(gdb) 
```

**Comment by Clark0** [comment]
s3-meta-sanitizer does not support .yaml config. fixed in the pr #704

**Comment by gaodayue** [comment]
@hillbun  You can try use a xml config file with the following content
```
<?xml version="1.0"?>
<yandex>
    <catalog>
        <name_space>byconity</name_space>
    </catalog>

    <catalog_service>
        <type>fdb</type>
        <fdb>
            <cluster_file>/etc/byconity/fdb/cluster-file</cluster_file>
        </fdb>
    </catalog_service>
</yandex>
```

**Comment by hillbun** [comment]
error when run clickhouse s3-meta-sanitizer -C /tmp/cnch-config.xml


```
2023.09.20 08:35:18.536245 <Information> S3MetaSanitizer: Skipping key byconity_PT_9723e211-beba-4f0f-911f-4d42bea793f1_191_444046623381127178_444046623381127178_0_444046410520199168 since there is no part id
2023.09.20 08:35:18.536250 <Information> S3MetaSanitizer: Skipping key byconity_PT_9723e211-beba-4f0f-911f-4d42bea793f1_191_444046624888455188_444046624888455188_0_444046568763424768 since there is no part id
2023.09.20 08:35:18.536255 <Information> S3MetaSanitizer: Skipping key byconity_PT_9723e211-beba-4f0f-911f-4d42bea793f1_191_444046634784129031_444046634784129031_0_444046410520199168 since there is no part id
2023.09.20 08:35:18.536260 <Information> S3MetaSanitizer: Skipping key byconity_PT_9723e211-beba-4f0f-911f-4d42bea793f1_191_444046636383207459_444046636383207459_0_444046568763424768 since there is no part id
2023.09.20 08:35:18.536266 <Information> S3MetaSanitizer: Skipping key byconity_PT_9723e211-beba-4f0f-911f-4d42bea793f1_191_444046646305357863_444046646305357863_0_444046410520199168 since there is no part id
2023.09.20 08:35:18.621857 <Error> S3MetaSanitizer: Code: 8067, e.displayText() = DB::Exception: Error whiling scanning data through FBDItrator. message: Transaction is too old to perform reads or be committed SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1c594a12 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xc85b4e0 in /opt/byconity/bin/clickhouse
2. DB::Catalog::MetastoreFDBImpl::FDBIterator::next() @ 0x160216d5 in /opt/byconity/bin/clickhouse
3. DB::S3MetaSanitizer::sanitizePartsMeta(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xcab1164 in /opt/byconity/bin/clickhouse
4. DB::S3MetaSanitizer::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xcab0e02 in /opt/byconity/bin/clickhouse
5. Poco::Util::Application::run() @ 0x1c519caa in /opt/byconity/bin/clickhouse
6. mainEntryClickhouseS3MetaSanitizer(int, char**) @ 0xcab1b3f in /opt/byconity/bin/clickhouse
7. main @ 0xc854128 in /opt/byconity/bin/clickhouse
8. __libc_start_main @ 0x2409b in /lib/x86_64-linux-gnu/libc-2.28.so
9. _start @ 0xc85392a in /opt/byconity/bin/clickhouse
 (version 21.8.7.1)
```

**Comment by hillbun** [comment]
use this image caoliu98/byconity:0.2.1

it is fixed
