### ISSUE TITLE
test case 10054_mv_refresh.sql coredump

### ISSUE THREAD

**Issue by dmthuc** [ByConity/ByConity#970]
query
```
refresh materialized view mv1.mv1 where toDate(event_date) < '2022-06-14';
```
```
#0  0x00007f805d509ce1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f805d4f3537 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x000000001fd635c1 in abort_message ()
#3  0x000000001fd62050 in __cxa_pure_virtual ()
#4  0x000000001a776234 in DB::MergeTreePartition::adjustPartitionKey(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) ()
#5  0x000000001a23da50 in DB::StorageMaterializedView::checkPartitionExpr(std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>) ()
#6  0x000000001a23ead6 in DB::StorageMaterializedView::refreshWhere(std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>, bool) ()
#7  0x0000000019931fa1 in DB::InterpreterRefreshQuery::execute() ()
#8  0x0000000019d9eeec in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) ()
#9  0x0000000019d9a918 in DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) ()
#10 0x000000001a9b5ff0 in DB::TCPHandler::runImpl() ()
```

**Comment by chenbay** [comment]
@dmthuc  closed if fixed?

**Comment by dmthuc** [comment]
The fix has been merged.
