### ISSUE TITLE
test case 02511_complex_literals_as_aggregate_function_parameters.sql trigger coredump

### ISSUE THREAD

**Issue by dmthuc** [ByConity/ByConity#972]
query 
```
SELECT funnelRep2(1, 2, 0, [0, 60000, 120000, 180000, 240000, 300000, 360000, 420000, 480000, 540000, 600000])(funnel_tmp_res.1, funnel_tmp_res.2) AS col2
FROM
(
    SELECT finderFunnel(600000, 1682956800, 345600, 1, 0, 0, 'Asia/Shanghai', 1)(multiIf(server_time < 1606406400, server_time, time > 2000000000, toUInt32(time / 1000), time), multiIf(time <= 2000000000, time * 1000, time), unifyNull(event = 'predefine_pageview'), unifyNull(event = 'predefine_pageview')) AS funnel_tmp_res
    FROM tob_apps AS et
    WHERE (tea_app_id = 41514) AND ((event = 'predefine_pageview') OR (event = 'predefine_pageview')) AND ((event_date >= '2023-05-02') AND (event_date <= '2023-05-06') AND (multiIf(server_time < 1606406400, server_time, time > 2000000000, toUInt32(time / 1000), time) >= 1682956800) AND (multiIf(server_time < 1606406400, server_time, time > 2000000000, toUInt32(time / 1000), time) <= 1683302999))
    GROUP BY et.hash_uid
);
```

```
#0  0x000000001a0b14fe in boost::multi_index::detail::bidir_node_iterator<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<DB::ColumnDescription, std::__1::allocator<DB::ColumnDescription> > > > boost::multi_index::detail::ordered_index_impl<boost::multi_index::member<DB::ColumnDescription, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, &DB::ColumnDescription::name>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::multi_index::detail::nth_layer<2, DB::ColumnDescription, boost::multi_index::indexed_by<boost::multi_index::sequenced<boost::multi_index::tag<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >, boost::multi_index::ordered_unique<boost::multi_index::member<DB::ColumnDescription, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, &DB::ColumnDescription::name>, mpl_::na, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::__1::allocator<DB::ColumnDescription> >, boost::mpl::vector0<mpl_::na>, boost::multi_index::detail::ordered_unique_tag, boost::multi_index::detail::null_augment_policy>::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const ()
#1  0x000000001a0c3827 in DB::ColumnsDescription::getPhysical(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const ()
#2  0x000000001ac5bf10 in DB::ExprAnalyzerVisitor::visitASTTableColumnReference(std::__1::shared_ptr<DB::IAST>&, DB::Void const&) ()
#3  0x000000001ac664d1 in DB::ColumnWithTypeAndName DB::ASTVisitorUtil::accept<DB::ColumnWithTypeAndName, DB::Void const>(std::__1::shared_ptr<DB::IAST>&, DB::ASTVisitor<DB::ColumnWithTypeAndName, DB::Void const>&, DB::Void const&) ()
#4  0x000000001ac5b896 in DB::ExprAnalyzerVisitor::process(std::__1::shared_ptr<DB::IAST>&) ()
#5  0x000000001ac6098f in DB::ExprAnalyzerVisitor::analyzeOrdinaryFunction(std::__1::shared_ptr<DB::ASTFunction>&) ()
#6  0x000000001ac5c90b in DB::ExprAnalyzerVisitor::visitASTFunction(std::__1::shared_ptr<DB::IAST>&, DB::Void const&)
    ()
#7  0x000000001ac65a81 in DB::ColumnWithTypeAndName DB::ASTVisitorUtil::accept<DB::ColumnWithTypeAndName, DB::Void const>(std::__1::shared_ptr<DB::IAST>&, DB::ASTVisitor<DB::ColumnWithTypeAndName, DB::Void const>&, DB::Void const&) ()
#8  0x000000001ac5b896 in DB::ExprAnalyzerVisitor::process(std::__1::shared_ptr<DB::IAST>&) ()
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x000000001ac6098f in DB::ExprAnalyzerVisitor::analyzeOrdinaryFunction(std::__1::shared_ptr<DB::ASTFunction>&) ()
#10 0x000000001ac5c90b in DB::ExprAnalyzerVisitor::visitASTFunction(std::__1::shared_ptr<DB::IAST>&, DB::Void const&)
    ()
#11 0x000000001ac65a81 in DB::ColumnWithTypeAndName DB::ASTVisitorUtil::accept<DB::ColumnWithTypeAndName, DB::Void const>(std::__1::shared_ptr<DB::IAST>&, DB::ASTVisitor<DB::ColumnWithTypeAndName, DB::Void const>&, DB::Void const&) ()
#12 0x000000001ac5b896 in DB::ExprAnalyzerVisitor::process(std::__1::shared_ptr<DB::IAST>&) ()
#13 0x000000001ac5b57f in DB::ExprAnalyzer::analyze(std::__1::shared_ptr<DB::IAST>, DB::Scope const*, std::__1::shared_ptr<DB::Context const>, DB::Analysis&, DB::ExprAnalyzerOptions) ()
#14 0x000000001ae89777 in DB::TypeAnalyzer::getType(std::__1::shared_ptr<DB::IAST const> const&) const ()
#15 0x000000001b0fca6e in DB::ProjectionPlanner::addColumn(std::__1::shared_ptr<DB::IAST>) ()
#16 0x000000001b1de69c in DB::ShareCommonExpression::rewriteImpl(std::__1::shared_ptr<DB::PlanNodeBase>, std::__1::shared_ptr<DB::Context>) ()
#17 0x000000001b1e0f03 in DB::ShareCommonExpression::rewrite(DB::QueryPlan&, std::__1::shared_ptr<DB::Context>) const
    ()
#18 0x000000001b1da535 in DB::Rewriter::rewritePlan(DB::QueryPlan&, std::__1::shared_ptr<DB::Context>) const ()
#19 0x000000001aed1569 in DB::PlanOptimizer::optimize(DB::QueryPlan&, std::__1::shared_ptr<DB::Context>, std::__1::vector<std::__1::shared_ptr<DB::Rewriter>, std::__1::allocator<std::__1::shared_ptr<DB::Rewriter> > > const&) ()
#20 0x000000001aed103e in DB::PlanOptimizer::optimize(DB::QueryPlan&, std::__1::shared_ptr<DB::Context>) ()
#21 0x0000000019b0eeca in DB::InterpreterSelectQueryUseOptimizer::buildQueryPlan() ()
#22 0x0000000019b0e3f7 in DB::InterpreterSelectQueryUseOptimizer::getSampleBlock() ()
#23 0x0000000019dc3537 in DB::executeQueryByProxy(std::__1::shared_ptr<DB::Context>, DB::HostWithPorts const&, std::__1::shared_ptr<DB::IAST> const&, DB::BlockIO&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#24 0x0000000019d9c79d in DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::IAST>, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*) ()
```

```
2023.12.17 03:38:10.399027 [ 833238 ] {} <Fatal> BaseDaemon: Address: 0x6407 Access: read. Address not mapped to object.
2023.12.17 03:38:10.399089 [ 833238 ] {} <Fatal> BaseDaemon: Stack trace: 0x1a0b14fe 0x1a0c3827 0x1ac5bf10 0x1ac664d1 0x1ac5b896 0x1ac6098f 0x1ac5c90b 0x1ac65a81 0x1ac5b896 0x1ac6098f 0x1ac5c90b 0x1ac65a81 0x1ac5b896 0x1ac5b57f 0x1ae89777 0x1b0fca6e 0x1b1de69c 0x1b1e0f03 0x1b1da535 0x1aed1569 0x1aed103e 0x19b0eeca 0x19b0e3f7 0x19dc3537 0x19d9c79d 0x19d9a918 0x1a9b5ff0 0x1a9c489c 0x1f79d4cc 0x1f79d9ac 0x1f884b3a 0x1f8826ec 0x7f83e51a7ea7 0x7f83e3c9fa2f
```

**Comment by FluorineDog** [comment]
has been fixed in recent changes.
