### ISSUE TITLE
Coredump when select from Dictionary due to query forwarding

### ISSUE THREAD

**Issue by dmthuc** [ByConity/ByConity#995]
```#0  0x000000001fd61d13 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
[Current thread is 29953 (LWP 2425)]
(gdb) bt
#0  0x000000001fd61d13 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#1  0x000000001a90a990 in DB::Connection::LoggerWrapper::get() ()
#2  0x000000001a900a4d in DB::Connection::connect(DB::ConnectionTimeouts const&) ()
#3  0x000000001a902afa in DB::Connection::getServerRevision(DB::ConnectionTimeouts const&) ()
#4  0x000000001a9257b1 in DB::MultiplexedConnections::sendQuery(DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, DB::ClientInfo const&, bool) ()
#5  0x00000000192007d9 in DB::RemoteQueryExecutor::sendQuery() ()
#6  0x000000001abaabc8 in DB::RemoteSource::tryGenerate() ()
#7  0x000000001a9f1d79 in DB::ISource::work() ()
#8  0x000000001abb04ba in DB::SourceWithProgress::work() ()
#9  0x000000001aa2acc1 in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::$_0, void ()> >(std::__1::__function::__policy_storage const*) ()
#10 0x000000001aa28d37 in DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*)
    ()
#11 0x000000001aa27d03 in DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) ()
#12 0x000000001aa33b9b in DB::PullingPipelineExecutor::pull(DB::Chunk&) ()
#13 0x000000001aa33d16 in DB::PullingPipelineExecutor::pull(DB::Block&) ()
#14 0x000000001aa221f4 in DB::PipelineExecutingBlockInputStream::readImpl() ()
#15 0x00000000191ed488 in DB::IBlockInputStream::read() ()
#16 0x00000000191eaa4b in DB::ConvertingBlockInputStream::readImpl() ()
#17 0x00000000191ed488 in DB::IBlockInputStream::read() ()
#18 0x0000000012539bd7 in DB::RangeHashedDictionary::loadData() ()
#19 0x00000000125397a4 in DB::RangeHashedDictionary::RangeHashedDictionary(DB::StorageID const&, DB::DictionaryStructure const&, std::__1::unique_ptr<DB::IDictionarySource, std::__1::default_delete<DB::IDictionarySource> >, DB::ExternalLo--Type <RET> for more, q to quit, c to continue without paging--
adableLifetime, bool) ()
#20 0x000000001254f045 in std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> > std::__1::__function::__policy_invoker<std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<DB::IDictionarySource, std::__1::default_delete<DB::IDictionarySource> >, std::__1::shared_ptr<DB::Context const>, bool)>::__call_impl<std::__1::__function::__default_alloc_func<DB::registerDictionaryRangeHashed(DB::DictionaryFactory&)::$_5, std::__1::unique_ptr<DB::IDictionary, std::__1::default_delete<DB::IDictionary> > (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<DB::IDictionarySource, std::__1::default_delete<DB::IDictionarySource> >, std::__1::shared_ptr<DB::Context const>, bool)> >(std::__1::__function::__policy_storage const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::DictionaryStructure const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<DB::IDictionarySource, std::__1::default_delete<DB::IDictionarySource> >&&, std::__1::shared_ptr<DB::Context const>&&, bool) ()
#21 0x0000000018ebf22c in DB::DictionaryFactory::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>, bool) const ()
#22 0x0000000019682445 in DB::ExternalDictionariesLoader::create(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const ()
#23 0x000000001968c878 in DB::ExternalLoader::LoadingDispatcher::loadSingleObject(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ExternalLoader::ObjectConfig const&, std::__1::shared_ptr<DB::IExternalLoadable const>) ()
#24 0x000000001968a7c7 in DB::ExternalLoader::LoadingDispatcher::doLoading(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::Th--Type <RET> for more, q to quit, c to continue without paging--
readGroupStatus>) ()
#25 0x000000001968eed2 in ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ExternalLoader::LoadingDispatcher::*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool, std::__1::shared_ptr<DB::ThreadGroupStatus> >(void (DB::ExternalLoader::LoadingDispatcher::*&&)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, bool, unsigned long, bool, std::__1::shared_ptr<DB::ThreadGroupStatus>), DB::ExternalLoader::LoadingDispatcher*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, unsigned long&, bool&, unsigned long&, bool&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&)::{lambda()#1}::operator()() ()
#26 0x000000000dbfb27f in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)
    ()
#27 0x000000000dbff55a in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::{lambda()#2}> >(void*) ()
#28 0x00007f80fa174ea7 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#29 0x00007f80f8c6ca2f in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by dmthuc** [comment]
Fix in latest commit
